[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Helpful headers (optional)
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"
